L : 10      # RF chains
use_cuda : True
dataset_type : "QUAD" # "Rayleigh"
Quad_data_path : 'DataGen/MU_MIMO/MU_MIMO/H_1200Channels_8B_12M_6N.mat'
Rayleigh_data_path : Rayleigh_dataset.pt.pt
train_size : 1000 #For IID data creation and Quadrigo Datasplit
valid_size : 100 #For IID data creation and Quadrigo Datasplit
test_size : 100 #For IID data creation and Quadrigo Datasplit
create_IID_dataset : False #only relevant if IID dataset chosen
B : 8      # Num of frequency bands for data creation
N : 6      # Num of users for data creation
M : 12     # Tx antennas for data creation


num_of_iter_pga : 100 # num classical pga iterations
num_of_iter_pga_unf : 5 # num unfolded pga iterations

# training parameters
train : True
mu_matrix : False
lr : 0.01
save_model_interval: 2500
epochs : 1000
batch_size : 100  # batch size
loss : "one_iter" # "all_iter" "some_iter"
start_train_model : null
eval_model : runs\QUAD_SET__8B__6N__12M__10L\D29_M12_h20_m13__K_5__loss_one_iter__WaConst_False__dWaOnes_False__Q_8__dWdApprox_False\PGA_model.pth

#dWd options
full_grad_Wd_iter : [0,4] #iterations on which to do full grad for dWd --- CURRENTLY HARD CODED TO BE OFF
approx_dWd : False
iters_to_approx : [1,3] #first iter is 0 (only if approx_dWd True)

#dWa options
Wa_constrained : False
dWa_G_I : False
dWa_G_Ones : False
stoch_dWa : False
Freq_bins_for_stoch_dWa : 8 #Instead of summing B freq bins, randomly choose Freq_bins_for_stoch_dWa bins (only if stoch_dWa True)
